In [11]:
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

In [12]:
Adata = pd.read_csv("USA.csv")
Adata.head()

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20201206,AK,35720.0,NaN,1042056.0,NaN,totalTestsViral,1077776.0,164.0,799.0,...,1077776,0,0,7b1d31e2756687bb9259b29195f1db6cdb321ea6,0,0,0,0,0,NaN
1,20201206,AL,269877.0,45962.0,1421126.0,NaN,totalTestsPeopleViral,1645041.0,1927.0,26331.0,...,1691003,12,0,19454ed8fe28fc0a7948fc0771b2f3c846c1c92e,0,0,0,0,0,NaN
2,20201206,AR,170924.0,22753.0,1614979.0,NaN,totalTestsViral,1763150.0,1076.0,9401.0,...,1785903,40,21,25fc83bffff5b32ba1a737be8e087fad9f4fde33,0,0,0,0,0,NaN
3,20201206,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,2140,0,0,8c39eec317586b0c34fc2903e6a3891ecb00469e,0,0,0,0,0,NaN
4,20201206,AZ,364276.0,12590.0,2018813.0,NaN,totalTestsPeopleViral,2370499.0,2977.0,28248.0,...,2383089,25,242,7cf59da9e4bc31d905e179211313d08879880a85,0,0,0,0,0,NaN

In [13]:
#checking columns names
Adata.columns

Index(['date', 'state', 'positive', 'probableCases', 'negative', 'pending',
       'totalTestResultsSource', 'totalTestResults', 'hospitalizedCurrently',
       'hospitalizedCumulative', 'inIcuCurrently', 'inIcuCumulative',
       'onVentilatorCurrently', 'onVentilatorCumulative', 'recovered',
       'dataQualityGrade', 'lastUpdateEt', 'dateModified', 'checkTimeEt',
       'death', 'hospitalized', 'dateChecked', 'totalTestsViral',
       'positiveTestsViral', 'negativeTestsViral', 'positiveCasesViral',
       'deathConfirmed', 'deathProbable', 'totalTestEncountersViral',
       'totalTestsPeopleViral', 'totalTestsAntibody', 'positiveTestsAntibody',
       'negativeTestsAntibody', 'totalTestsPeopleAntibody',
       'positiveTestsPeopleAntibody', 'negativeTestsPeopleAntibody',
       'totalTestsPeopleAntigen', 'positiveTestsPeopleAntigen',
       'totalTestsAntigen', 'positiveTestsAntigen', 'fips', 'positiveIncrease',
       'negativeIncrease', 'total', 'totalTestResultsIncrease', 'posNeg',
       'deathIncrease', 'hospitalizedIncrease', 'hash', 'commercialScore',
       'negativeRegularScore', 'negativeScore', 'positiveScore', 'score',
       'grade'],
      dtype='object')

In [14]:
#Re-organized columns 
filled = Adata[["state", "totalTestResults", "totalTestsAntibody", "recovered", "positive","positiveTestsAntibody"]]
filled.head()

,state,totalTestResults,totalTestsAntibody,recovered,positive,positiveTestsAntibody
0,AK,1077776.0,NaN,7165.0,35720.0,NaN
1,AL,1645041.0,NaN,168387.0,269877.0,NaN
2,AR,1763150.0,NaN,149490.0,170924.0,NaN
3,AS,2140.0,NaN,NaN,0.0,NaN
4,AZ,2370499.0,370928.0,56382.0,364276.0,NaN

In [15]:
#Finding average of hit, run and strikeouts for each team 

Covid_positive= filled.groupby("state").positive.mean()
Positive_Antibody= filled.groupby("state").positiveTestsAntibody.mean()
Total_Covid_Test= filled.groupby("state").totalTestResults.mean()
Total_Antibody_Test= filled.groupby("state").totalTestsAntibody.mean()
Covid_recovered= filled.groupby("state").recovered.mean()

B_Analysis = pd.DataFrame({"Covid_positive":(Covid_positive),
                        "Positive_Antibody":(Positive_Antibody),
                        "Total_Covid_Test":(Total_Covid_Test),
                        "Total_Antibody_Test":(Total_Antibody_Test),
                        "Covid_recovered":(Covid_recovered)
                        })
B_Analysis= B_Analysis.sort_values("state",ascending=True)
B_Analysis["Covid_positive"] = B_Analysis["Covid_positive"].astype(float).map("{:.2f}".format)
B_Analysis["Positive_Antibody"] = B_Analysis["Positive_Antibody"].astype(float).map("{:.2f}".format)
B_Analysis["Total_Covid_Test"] = B_Analysis["Total_Covid_Test"].astype(float).map("{:.2f}".format)
B_Analysis["Total_Antibody_Test"] = B_Analysis["Total_Antibody_Test"].astype(float).map("{:.2f}".format)
B_Analysis["Covid_recovered"] = B_Analysis["Covid_recovered"].astype(float).map("{:.2f}".format)
B_Analysis.head(5)

AttributeError: 'float' object has no attribute '2f'

In [ ]:
#Fill nan values with 0
Nan_filled= B_Analysis.replace('NaN','0')
Nan_filled.head(5)

In [ ]:
Nan_filled.dtypes

In [ ]:
#Save table as csv file called: Obesity_percentage
Nan_filled.to_csv('USA_cleaned.csv')